# Generated by Django 5.0.6 on 2026-04-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('ATO', 'ATO 9:00-9:15'), ('CONTINUOUS', 'Liên tục 9:15-11:30 / 13:00-14:30'), ('ATC', 'ATC 14:30-14:45'), ('CLOSED', 'Đóng cửa')], max_length=15)),
                ('date', models.DateField()),
                ('is_trading_day', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_sessions',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('exchange', models.CharField(choices=[('HOSE', 'HOSE'), ('HNX', 'HNX'), ('UPCOM', 'UPCOM')], max_length=10)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_vn30', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ceiling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('bid_price_1', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('bid_vol_1', models.BigIntegerField(null=True)),
                ('bid_price_2', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('bid_vol_2', models.BigIntegerField(null=True)),
                ('bid_price_3', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('bid_vol_3', models.BigIntegerField(null=True)),
                ('ask_price_1', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ask_vol_1', models.BigIntegerField(null=True)),
                ('ask_price_2', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ask_vol_2', models.BigIntegerField(null=True)),
                ('ask_price_3', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ask_vol_3', models.BigIntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market_data.stock')),
            ],
            options={
                'db_table': 'price_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stock', '-timestamp'], name='price_snaps_stock_i_b7a5bc_idx')],
            },
        ),
    ]
