# Generated by Django 5.0.6 on 2026-04-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_outlook', models.CharField(default='NEUTRAL', max_length=20)),
                ('summary', models.TextField()),
                ('evaluations', models.JSONField(default=list)),
                ('best_strategy', models.CharField(blank=True, max_length=300)),
                ('warning', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
