# Generated by Django 5.0.6 on 2026-04-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bot_username', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total_value', models.BigIntegerField()),
                ('pnl_pct', models.FloatField()),
                ('matched_orders', models.IntegerField(default=0)),
                ('trades_today', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-pnl_pct'],
                'unique_together': {('date', 'bot_username')},
            },
        ),
    ]
